/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./../components/ui/BaseButton.vue')['default']
    BaseInput: typeof import('./../components/ui/BaseInput.vue')['default']
    BaseModal: typeof import('./../components/common/BaseModal.vue')['default']
    BaseSelect: typeof import('./../components/ui/BaseSelect.vue')['default']
    LoadingOverlay: typeof import('./../components/common/LoadingOverlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
